# -*- coding: utf-8 -*-
"""ERP_system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q8CNShK25O5dq8QDU_YK3ZdRL4vMZ6Mt
"""

class erp_system():
  def __init__(self):
    self.stock = []
    self.barkod = 1000
    self.balans = 0

  def add_items(self,ad: str, say: int, alis_qiymeti: int):
    satis_qiymeti = alis_qiymeti*1.5
    barkod = self.barkod
    self.barkod+=1
    self.stock.append({'Mehsulun adi': ad,
                       'Mehsulun sayi': say,
                       'Mehsulun maya deyeri': alis_qiymeti,
                       'Mehsulun satis qiymeti': satis_qiymeti,
                       'Mehsulun barkodu': barkod})
    print(f'Mehsullar sisteme yuklendi')

  def show_items(self):
    for item in self.stock:
      print(item)


  def sell(self, mehsulun_adi):
    for item in self.stock:
      for t in item:
        if t == 'Mehsulun adi':
          if item['Mehsulun adi'] == mehsulun_adi:
            item['Mehsulun sayi'] -= 1
            self.balans+=item['Mehsulun satis qiymeti']
    print(f'{mehsulun_adi} mehsulunuz satildi :)')

  def sale(self,mehsulun_adi, endirim_faizi):
    for item in self.stock:
      for t in item:
        if t == 'Mehsulun adi':
          if item['Mehsulun adi'] == mehsulun_adi:
            item['Mehsulun sayi'] -= 1
            self.balans+=(item['Mehsulun satis qiymeti'] -item['Mehsulun satis qiymeti']*(endirim_faizi/100))
    print(f'{mehsulun_adi} mehsuluna {endirim_faizi} faiz endirim edildi, nus olsun :)')

  def show_balance(self):
    print(f'Sizin cari balansiniz - {self.balans}')

magaza = erp_system()

magaza.add_items('Balli tort',5,10)

magaza.add_items('Snickers Tortu',7,12)

magaza.add_items('Mars tortu', 4, 9)

magaza.show_items()

magaza.sell('Snickers Tortu')

magaza.show_items()

magaza.show_balance()

magaza.sale('Balli tort',25)

magaza.show_balance()

